version: '3'

services:
    wordpress:
        build:
            dockerfile: Dockerfile.develop
            context: .
        depends_on:
            - mysql
        restart: on-failure
        volumes:
            - wordpress:/var/www/html
            - ./:/var/www/html/wp-content/themes/wordpress-block-theme
            - ./storage:/var/www/html/wp-content/uploads/wordpress-block-theme
            - /var/www/html/wp-content/themes/twentytwenty
        ports:
            - "8080:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            ENVIRONMENT: development
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DEBUG: 1
            WORDPRESS_CONFIG_EXTRA: |
                define( 'WP_DEBUG_LOG', true );
                define( 'FS_METHOD', 'direct' );
        links:
            - mysql
    wordpress-cli:
        image: wordpress:cli-php8.2
        depends_on:
            - wordpress
        restart: on-failure
        volumes:
            - wordpress:/var/www/html
            - ./:/var/www/html/wp-content/themes/wordpress-block-theme
        command:
            - bash
            - -c
            - |
                wp core install \
                    --url=localhost:8080 \
                    --title="WordPress Block Theme" \
                    --admin_user=wordpress \
                    --admin_email=martin@moonwalkingbits.com \
                    --admin_password=wordpress \
                    --skip-email \
                    --allow-root
                wp language core install --activate --allow-root sv_SE
                wp post delete 1 2 3 --force --allow-root
                wp plugin uninstall akismet hello --allow-root
                wp theme activate wordpress-block-theme --allow-root
        user: root
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DEBUG: 1
            WORDPRESS_CONFIG_EXTRA: |
                define( 'WP_DEBUG_LOG', true );
                define( 'FS_METHOD', 'direct' );
    mysql:
        image: mysql:5.7
        ports:
            - '3306:3306'
        platform: linux/x86_64
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: wordpress
volumes:
    wordpress:
